# Generated by Django 3.0.5 on 2020-05-03 11:40

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200503_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='canvas_token',
            field=fernet_fields.fields.EncryptedTextField(verbose_name=models.CharField(blank=True, default='', max_length=2000)),
        ),
    ]
