# Generated by Django 3.0.5 on 2020-05-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compvas', '0003_cachsites'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachsites',
            name='course_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cachsites',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
