# Generated by Django 3.0.5 on 2020-05-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compvas', '0005_cachsites_image_download_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachsites',
            name='image_download_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
