# Generated by Django 3.0.5 on 2020-05-05 08:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compvas', '0006_auto_20200504_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachsites',
            name='frontpage_json',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
    ]
