# Generated by Django 3.0.5 on 2020-05-10 03:22

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compvas', '0007_cachsites_frontpage_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachsites',
            name='files_json',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
    ]
