# Generated by Django 3.0.5 on 2020-05-26 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('comment_link', models.ManyToManyField(related_name='_comments_comment_link_+', to='message.Comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='comment_link',
            field=models.ManyToManyField(to='message.Comments'),
        ),
    ]
