# Generated by Django 3.0.5 on 2020-04-27 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='message.Posts'),
        ),
    ]
