# Generated by Django 3.0.5 on 2020-04-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20200427_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comment_link',
        ),
        migrations.AddField(
            model_name='posts',
            name='comment_link',
            field=models.ManyToManyField(default=None, null=True, to='message.Comments'),
        ),
    ]
