# Generated by Django 3.0.5 on 2020-04-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20200428_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comment_link',
            field=models.ManyToManyField(to='message.Comments'),
        ),
    ]
