# Generated by Django 3.0.5 on 2020-04-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20200428_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_link',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_link',
            field=models.ManyToManyField(related_name='_comments_comment_link_+', to='message.Comments'),
        ),
    ]
