# Generated by Django 3.0.5 on 2020-04-27 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_comments_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_link',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.Comments'),
        ),
    ]
