# Generated by Django 3.0.5 on 2020-04-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
